# Generated by Django 5.0.7 on 2024-08-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_rating_unique_together_alter_product_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='popularity',
        ),
    ]
