# Generated by Django 5.0.7 on 2024-08-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_rating_unique_together_alter_product_table'),
        ('user', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(default=1, on_delete=models.SET('deleted'), to='product.product'),
            preserve_default=False,
        ),
    ]
