# Generated by Django 5.0.7 on 2024-08-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_sity_city_rename_sity_user_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='cities',
        ),
    ]
